# Serena Project Configuration for Dotfiles
# Auto-updated: Mon Aug 04 2025
project_name: dotfiles

description: |
  Personal dotfiles repository containing cross-platform configurations
  for development tools, shell environments, and productivity applications.
  Supports macOS and Linux environments.

project_type: configuration
category: dotfiles

platforms:
  - macos
  - linux

components:
  - nvim (Neovim configuration)
  - tmux (Terminal multiplexer)
  - zsh (Shell configuration)
  - wezterm (Terminal emulator)
  - aerospace (Window manager)
  - augment (AI assistant)
  - opencode (Agent framework)
  - scripts (Automation tools)

documentation:
  readme: README.md
  main_docs: docs/
  guides:
    - docs/serena-integration-guide.md
    - docs/serena-mcp-best-practices.md

verification:
  manual_testing: true
  cross_platform_testing: required

automation:
  auto_update: true
  backup_before_changes: true

patterns:
  - cross_platform_compatibility
  - modular_configuration
  - automated_setup
  - version_controlled_dotfiles

ignore_all_files_in_gitignore: true
ignored_paths:
  - '.DS_Store'
  - '*.log'
  - 'node_modules/**'
  - '.git/**'
  - '.venv/**'
  - 'venv/**'
  - '__pycache__/**'
  - '*.tmp'
  - '*.temp'

read_only: false

languages:
  - shell
  - lua

initial_prompt: |
  You are working on a personal dotfiles project, primarily configuring shell and Lua for a cross-platform development environment (macOS & Linux).
  Prioritize simplicity, safety, recoverability, and automation.
  There is no complex backend code or frontend framework, only focus on optimizing the personal development environment.
  Always carefully check shell and Lua files for syntax errors and keep everything cross-platform.
