# AeroSpace Configuration for DevOps Backend Development
# Tối ưu cho backend development với multiple terminals, IDE, browsers, và monitoring tools

# Cấu hình chung
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus (hữu ích cho multi-monitor setup)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Startup commands
after-startup-command = [
    # JankyBorders để highlight focused windows
    'exec-and-forget borders active_color=0xff7dc4e4 inactive_color=0xff363a4f width=3.0'
]

# Workspace names - tối ưu cho backend dev workflow
[workspace-to-monitor-force-assignment]
0 = 'main'    # Social
1 = 'main'    # Terminal/Development
2 = 'main'    # Browser/Documentation  
3 = 'main'    # IDE/Code
4 = 'main'    # Database/Redis clients
5 = 'main'    # Monitoring/Logs
6 = 'main'    # 2nd monitor
7 = 'main'    # 3rd monitor

# Key bindings - sử dụng Option làm modifier
[mode.main.binding]
# Reload config
alt-r = 'reload-config'

# Terminal và applications
alt-e = 'exec-and-forget open -n /Applications/WezTerm.app/'
alt-c = 'exec-and-forget open -n "/Applications/Google Chrome.app"'
alt-shift-c = 'exec-and-forget open -n "/Applications/Cursor.app/"'
alt-x = 'exec-and-forget open -n "/Applications/Firefox.app/"'
alt-s = 'exec-and-forget open -n "/Applications/Safari.app/"'
alt-v = 'exec-and-forget open -n "/Applications/Visual Studio Code.app"'

# Social 
alt-d = 'exec-and-forget open -n "/Applications/Discord.app/"'
alt-w = 'exec-and-forget open -n "/Applications/WhatsApp.app/"'
alt-z = 'exec-and-forget open -n "/Applications/Zalo.app/"'

# Navigation between windows (vim-like)
alt-h = 'focus left'
alt-j = 'focus down' 
alt-k = 'focus up'
alt-l = 'focus right'

# Close windows
alt-q = 'close'
alt-shift-q = 'close-all-windows-but-current'

# Layout controls
alt-space = 'layout floating tiling'  # Toggle floating/tiling
alt-f = 'fullscreen'
alt-t = 'layout tiles'
alt-shift-t = 'layout accordion'

# Move windows between workspaces
alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2' 
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'

# Switch to workspace-to-monitor-force-assignment
alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

# Move windows within workspace
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize windows
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Window arrangement - sử dụng join-with thay vì split
alt-shift-minus = 'join-with left'
alt-shift-equal = 'join-with right'
alt-shift-backslash = 'join-with up'
alt-shift-slash = 'join-with down'

# Monitor navigation (for multi-monitor setups)
alt-ctrl-h = 'focus-monitor left'
alt-ctrl-l = 'focus-monitor right'
alt-ctrl-shift-h = 'move-node-to-monitor left'
alt-ctrl-shift-l = 'move-node-to-monitor right'

# Backend development specific shortcuts
alt-shift-d = 'exec-and-forget open -n "/Applications/DBeaver.app"'  # DBeaver database client
alt-m = 'exec-and-forget open -n "/Applications/MySQLWorkbench.app"'  # MySQL Workbench
alt-a = 'exec-and-forget open -n "/System/Applications/Utilities/Activity Monitor.app"'  # System monitoring
alt-shift-s = 'exec-and-forget screencapture -i -c'  # Screenshot to clipboard

# Auto-assign applications to workspaces
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'com.vng.zalo'
run = 'move-node-to-workspace 0'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
run = 'move-node-to-workspace 4'  

[[on-window-detected]]
if.app-id = 'com.oracle.workbench.MySQLWorkbench'
run = 'move-node-to-workspace 4' 

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.docker.docker'
run = 'move-node-to-workspace 4'  # Docker to workspace 4

# Exec environment for development tools
[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:${PATH}'

# Gaps configuration - professional look
[gaps]
inner.horizontal = 24
inner.vertical = 24
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12
