# Serena Configuration
# Auto-updated: Mon Aug  4 17:37:52 +07 2025
read_only: true

# Dashboard Configuration
dashboard:
  enabled: true
  port: 24282
  web_dashboard_open_on_launch: true

# Logging Configuration
logging:
  level: info
  file: serena.log

# Performance & Statistics
record_tool_usage_stats: true
token_count_estimator: enabled

# Security Configuration
security:
  allowed_file_extensions: 
    - ".sh"
    - ".lua" 
    - ".md"
    - ".yml"
    - ".yaml"
    - ".json"
    - ".py"
    - ".js"
    - ".ts"
    - ".go"
    - ".toml"
    - ".conf"
  forbidden_paths: 
    - "/etc"
    - "/var"
    - "~/.ssh"
    - ".git"
  max_file_size: "5MB"
  audit_logging: true

# Tool Configuration
tools:
  execute_shell_command:
    enabled: false
    restricted_commands: 
      - "rm -rf"
      - "dd"
      - "shutdown"
      - "reboot"
      - "mkfs"
      - "fdisk"
  find_symbol:
    enabled: true
  replace_lines:
    enabled: false
  read_file:
    enabled: true
  insert_at_line:
    enabled: false
  search_for_pattern:
    enabled: true
  get_symbols_overview:
    enabled: true

# Project Configuration
project:
  auto_index: true
  memory_dir: .serena/memories
  ignore_all_files_in_gitignore: true
  ignore_paths:
    - ".git"
    - "node_modules"
    - "__pycache__"
    - ".venv"
    - "venv"
    - ".DS_Store"
    - "*.log"

# Projects Registry
projects:
  dotfiles:
    path: "/Users/killerkidbo/dotfiles"
    name: dotfiles
    active: true
