# Serena Configuration
read_only: false
dashboard:
  enabled: true
  port: 24282
logging:
  level: info
  file: serena.log
tools:
  execute_shell_command:
    enabled: true
    restricted_commands: []
  find_symbol:
    enabled: true
  replace_lines:
    enabled: true
  read_file:
    enabled: true
  insert_at_line:
    enabled: true
project:
  auto_index: false
  memory_dir: .serena/memories