-- Load all plugin configurations
return {
  require("plugins.autopairs"),
  require("plugins.bufferline"),
  require("plugins.colorscheme"),
  require("plugins.comment"),
  require("plugins.completions"),
  require("plugins.dap"),
  require("plugins.fugitive"),
  require("plugins.gitsigns"),
  require("plugins.indent-blankline"),
  -- require("plugins.lsp"), -- Disabled: conflicts with NvChad LSP setup
  require("plugins.lualine"),
  require("plugins.markdown-preview"),
  require("plugins.markdown"),
  require("plugins.mason"),
  require("plugins.neo-tree"),
  require("plugins.noice"),
  require("plugins.nvim-colorizer"),
  require("plugins.nvim-notify"),
  require("plugins.pomo"),
  require("plugins.surround"),
  require("plugins.telescope-file-browser"),
  require("plugins.telescope-project"),
  require("plugins.telescope"),
  require("plugins.treesitter"),
  require("plugins.ufo"),
  require("plugins.web-devicons"),
  require("plugins.which-key"),
}
